### ISSUE TITLE
Publish the library onto Maven Central

### ISSUE THREAD

**Issue by krmahadevan** [adiralashiva8/testng-metrics#4]
The library in its current form cannot be consumed by others as a TestNG listener.
It needs to be published on to Maven central so that others can consume it as well.

To integrate with Travis, you can refer to https://github.com/marketplace/travis-ci

You can follow the below steps to get Travis to publish into Maven Central 
https://github.com/making/travis-ci-maven-deploy-skelton

**Comment by adiralashiva8** [comment]
@krmahadevan I have tried to follow the steps mentioned [here](https://github.com/making/travis-ci-maven-deploy-skelton). But I was strucked at `openssl` commands:

I have tried by installing ssl but no luck still I'm getting errors in my machine like : 
```
~/.gnupg/pubring.gpg: No error
13932:error:02001003:system library:fopen:No such process:.\crypto\bio\bss_file.c:356:fopen('~/.gnupg/pubring.gpg','rb')
13932:error:20074002:BIO routines:FILE_CTRL:system lib:.\crypto\bio\bss_file.c:358:
```

Is there any other way to upload artificats to maven central repo apart from travis(simple and easy way :) )?

**Comment by krmahadevan** [comment]
@adiralashiva8 - Nope. I am not aware of alternatives. But you can google up. I am pretty sure there must be other ways as well. I found this way to be easy enough. You just need to first setup your `gpg` and then the rest should be straight forward.  I am not sure what OS you are on.

**Comment by adiralashiva8** [comment]
Mine is windows. I have gone through steps available in couple of websites. Since I dont have much knowledge I couldnot make it out.
FYI created issue in sonartype and it got approved - https://issues.sonatype.org/browse/OSSRH-46347

**Comment by adiralashiva8** [comment]
I have uploaded repo to nexus. You can find uploaded info here - https://oss.sonatype.org/content/repositories/snapshots/com/github/adiralashiva8/testng-metrics/

I have gone through steps metioned in https://stackoverflow.com/questions/28846802/how-to-manually-publish-jar-to-maven-central - Answer By - Benoit Vanalderweireldt

Waiting for sync of repo. Thanks a lot @krmahadevan

**Comment by adiralashiva8** [comment]
Need to do some changes in report - holding upload artifact to central

**Comment by adiralashiva8** [comment]
Central sync is activated for com.github.adiralashiva8. For more info please refer ticket - https://issues.sonatype.org/browse/OSSRH-46347

Nexus Repo - https://oss.sonatype.org/#nexus-search;quick~testng-metrics

**Comment by adiralashiva8** [comment]
Now artifact is in maven repository - https://mvnrepository.com/search?q=com.github.adiralashiva8
