### ISSUE TITLE
Test Metrics: Missing dataprovider info in test 

### ISSUE THREAD

**Issue by saurabhgupta94** [adiralashiva8/testng-metrics#8]
Missing data provider in test info. 

for a end user, the tool should display the information of the parameters provided with the data provider. 

Current observation : Tool displays the same test name for data provider tests. 
Expected to be : Tool should display the parameters with the test.

**Comment by adiralashiva8** [comment]
@saurabhgupta94 Fixed at this pull request https://github.com/adiralashiva8/testng-metrics/pull/10
