### ISSUE TITLE
Class Metrics: Test Method column includes counts of @Before & @After methods

### ISSUE THREAD

**Issue by saurabhgupta94** [adiralashiva8/testng-metrics#9]
The count of test must be including be only including no of Test, Not @Before & @After Method in Class Metrics.

This is a minor change which can be fixed and should be made available for next version. 

Thanks.

**Comment by adiralashiva8** [comment]
@saurabhgupta94 Fixed at this pull request https://github.com/adiralashiva8/testng-metrics/pull/10
